name: Run tests

on:
  push:
    branches:
      - main
      - devops/threemay
  pull_request:
    branches: 
      - main 


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [12.x, 14.x]
        # mongodb-version: ['4.0', '4.2', '4.4']
        node-version: [14.x]
        mongodb-version: ['4.4']

    steps:
    - name: ----- Git checkout -----
      uses: actions/checkout@v2

    - name: ----- Use Node.js ${{ matrix.node-version }} -----
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: ----- Start MongoDB -----
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        # default port 27017
        mongodb-port: 27017

    - run: mongorestore --version
    
    # - run: npm install

    # - run: npm test
    #   env:
    #     CI: true
