name: Run tests

on:
  push:
    branches:
      - main
      - devops/threemay
  pull_request:
    branches: 
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: development
      PORT: 8080
      DB_URL: mongodb://localhost:27017/storekeeper
      DATABASE: storekeeper
      COLLECTION: users
      bsonPATH: ./dbDump/users.bson

    strategy:
      matrix:
        # node-version: [12.x, 14.x]
        # mongodb-version: ['4.0', '4.2', '4.4']
        node-version: [14.x]
        mongodb-version: ['4.4']

    steps:
    - name: ----- Git checkout -----
      uses: actions/checkout@v2

    - name: ----- Use Node.js ${{ matrix.node-version }} -----
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: ----- Create .env -----
      run: touch .env && echo NODE_ENV=${{ env.NODE_ENV }} > .env && 
           echo PORT=${{ env.PORT }} >> .env && 
           echo NODE_ENV=${{ env.DB_URL }} >> .env && 
           cat .env

    - name: ----- Start MongoDB -----
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        # default port 27017
        mongodb-port: 27017

    - name: ----- mongorestore -----
      run: mongorestore -d {{ env.DATABASE }} -c {{ env.COLLECTION }} {{ env.bsonPATH }} 
    
    - run: yarn 

    - run: yarn build

    - run: yarn test